### ISSUE TITLE
Type error on run in getFullyQualifiedClassNameFromFile

### ISSUE THREAD

**Issue by francislavoie** [spatie/laravel-database-cleanup#14]
`Type error: Return value of Spatie\ModelCleanup\CleanUpModelsCommand::getFullyQualifiedClassNameFromFile() must be of the type string, null returned`

This seems to happen if when using a glob for the models config, there are some files that don't contain classes (such as traits for example). It should probably filter those out.

The config I'm using is `app_path('Models/*'),`

**Comment by freekmurze** [comment]
We'll handle this in #15
