### ISSUE TITLE
[PROPOSAL] Allow configurable delete command

### ISSUE THREAD

**Issue by tomschlick** [spatie/laravel-database-cleanup#2]
- [x] I have read and understood the [contributors guide]().
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have checked that the bug-fix I am reporting can be replicated.

---

It would be fantastic if you could configure the method to delete these items. Right now it calls 

``` php
$class::cleanUp($class::query())->delete();
```

If we could configure the `->delete()` method of that it would allow you to run a periodic check to `->purge()` soft deleted items.

For instance I could say "1 year after I have soft-deleted this model, clean it up by purging it from the database".

Right now I'm not sure of the best way to implement this for a PR. 

**Option A** could be a $cleanup_method variable on the model with a default of 'delete';

**Option B** could be adding a cleanupMethod() function to the interface but that would be a breaking change for anyone already using this... However it is only a few hours old so I'm not sure how you feel about it...

**Comment by freekmurze** [comment]
Thanks for your proposal. Our packages are primarily built for use on our own projects. On those projects we never used soft deletion. 

I'd like this package simple, so probably won't accept a PR that adds complexity for supporting soft deletion. 

Of course your free to fork this package and maintain your own version that support soft deletions.
