### ISSUE TITLE
BUG / QUESTION InvalidArgumentException matching PHP version on composer require

### ISSUE THREAD

**Issue by blomdahldaniel** [spatie/laravel-database-cleanup#3]
**In raising this issue, I confirm the following (please check boxes):**
- [x] I have read and understood the [contributors guide]().
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have checked that the bug-fix I am reporting can be replicated.

---
### Description of the problem

I am on a server with PHP 5.6.10.0
When I run: `composer require spatie/laravel-model-cleanup` it yields the error:

> [InvalidArgumentException]
> Could not find package spatie/laravel-model-cleanup at any version matching your PHP version 5.6.10.0

How come I cannot install this package?
What can I do to fix this? And where does it say what php version is required for this package?

Note: Composer works just fine in any other case (just pulled in your laravel-backup without problem ;) )

**Comment by sebastiandedeyne** [comment]
This package requires php7, so it won't be installable on a server with 5.6.

**Comment by blomdahldaniel** [comment]
Okey, that is sad news for me then.
Please add information about this to the readme so that users like me can get that info.

This seems to be some awesome stuff.. 👍

**Comment by kabircse** [comment]
It would be better, if it follow the backward compatibility.

**Comment by freekmurze** [comment]
@blomdahldaniel For any package, not only ours, you can check `composer.json` for the required PHP version.

Almost every package we put out requires PHP 7.0 or higher.

**Comment by blomdahldaniel** [comment]
@freekmurze aah yeah right that is true, hadn't thought of that. While I've got you - thanks for your talk on Laracon US. :)
