### ISSUE TITLE
Can I take v2 and maintain it as a separate package?

### ISSUE THREAD

**Issue by dmason30** [spatie/laravel-database-cleanup#40]
Hi :wave:,

I have upgraded to v3 on my projects that are PHP 7.4 compatible and its great. However, some of my work projects are stuck on PHP 7.3 for a while yet due to security protocols but we still upgrade laravel when we can (e.g. 8.x) and the directories feature was useful in our DDD projects.

I was wondering If I could please extract what was the last released v2 code and release it as a separate package and maintain it. I will obviously credit and link to this package where needed. There might be some refactoring but the code will be largely the same. I just wanted to ask permission so that I don't end up in a _Laracatch_ situation 👀. 

Thanks,

Dan

**Comment by jochensengier** [comment]
You can bypass the missing directories feature in v3 really easy if you want to...

Add the following code in the `boot()` method of your `AppServiceProvider`

```
$models = Cache::rememberForever('modelsForCleanUp', function () {
	$directory = new \RecursiveDirectoryIterator(base_path('app/Models'), \RecursiveDirectoryIterator::SKIP_DOTS);
	$iterator  = new \RecursiveIteratorIterator($directory);

	return collect($iterator)->map(function ($file) {
		return Str::of($file->getPathname())
				->after(base_path())
				->before('.php')
				->replace('/', '\\')
				->replace('\app\\', 'App\\')
				->__toString();
	})->flatten()->map(fn ($className) => new $className)->filter(function ($modelClass) {
		return in_array('Spatie\ModelCleanup\GetsCleanedUp', class_implements($modelClass));
	})->map(fn ($modelClass) => get_class($modelClass))->toArray();
});

config()->set('model-cleanup.models', $models);
```
