### ISSUE TITLE
unable to locate the CleanupConfig class

### ISSUE THREAD

**Issue by meyer59** [spatie/laravel-database-cleanup#43]
Hi
I am unable to locate the `CleanupConfig` class mentionned in the readme
```
public function cleanUp(CleanupConfig $config): void
     {
         $config->olderThanDays(5);
     }
```
phpstorm also doesnt find it.
Thank you for your help

**Comment by freekmurze** [comment]
It exists: https://github.com/spatie/laravel-model-cleanup/blob/592e7af38703f27d1086f852c3f22595cf67b882/src/CleanupConfig.php
