### ISSUE TITLE
[PROPOSAL] Force delete on models

### ISSUE THREAD

**Issue by antonkomarev** [spatie/laravel-database-cleanup#6]
**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide]().
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
- [x] I have checked that the bug-fix I am reporting can be replicated.

---

### Description of the proposal

Extend `CleanUpModelsCommand` to allow perform `forceDelete` for models. I see several ways to do it:

1. Defined what models should use `forceDelete` on `cleanUp` in config file.
2. Define model property\method which will mean that `forceDelete` must be used.
3. Define it in console command optional attribute (not so flexible solution).
4. One more complex idea is make something like `cleanUpStrategies` and garbage collector will choose which one should be used right now. For example every week common delete will be performed for model `Document` with `draft` state, but monthly all soft deleted `Document` records of `draft` state from previous month should be force deleted. Each model should have own strategies, described as methods.

That's proposal was introduced in #2 but I've described all the ways to implement it, and hope you will change your mind in a future and extend functionality.

**Comment by freekmurze** [comment]
Thank you for this proposal.

I don't see us using soft deletes any time soon, so we're probably not going to invest time in this. 

If you need this feature, fork the package.
