### ISSUE TITLE
Upgrade required nikic/php-parser package to ^3.0

### ISSUE THREAD

**Issue by jochensengier** [spatie/laravel-database-cleanup#9]
Hi Freek

Not really an issue or a bug, but would it be possible to switch to version `^3.0` of the required `nikic/php-parser` package instead of the current `^2.0` version?

Downgrading to `v2.1.1` works fine for now.

_Thanks for all the great packages!_

**Comment by freekmurze** [comment]
There seems to be a breaking change in `nikic/php-parser` v2 branch.

I've tested our package with `v3` of that package and it seems to work.

The latest version of our package now allow for the usage of `v3`.
